
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: antrea
  name: externalentities.crd.antrea.io
spec:
  group: crd.antrea.io
  names:
    kind: ExternalEntity
    plural: externalentities
    shortNames:
      - ee
    singular: externalentity
  scope: Namespaced
  versions:
    - name: v1alpha2
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                endpoints:
                  items:
                    properties:
                      ip:
                        pattern: ^(((([1]?\d)?\d|2[0-4]\d|25[0-5])\.){3}(([1]?\d)?\d|2[0-4]\d|25[0-5]))|([\da-fA-F]{1,4}(\:[\da-fA-F]{1,4}){7})|(([\da-fA-F]{1,4}:){0,5}::([\da-fA-F]{1,4}:){0,5}[\da-fA-F]{1,4})$
                        type: string
                      name:
                        type: string
                    type: object
                  type: array
                externalNode:
                  type: string
                ports:
                  items:
                    properties:
                      name:
                        type: string
                      port:
                        x-kubernetes-int-or-string: true
                      protocol:
                        type: string
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
      served: false
      storage: false
