# permissions for end users to edit clusterclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterclaim-editor-role
rules:
- apiGroups:
  - mcs.crd.antrea.io
  resources:
  - clusterclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcs.crd.antrea.io
  resources:
  - clusterclaims/status
  verbs:
  - get
