# permissions for end users to edit federations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federation-editor-role
rules:
- apiGroups:
  - mcs.crd.antrea.io
  resources:
  - federations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcs.crd.antrea.io
  resources:
  - federations/status
  verbs:
  - get
