# permissions for end users to view federations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federation-viewer-role
rules:
- apiGroups:
  - mcs.crd.antrea.io
  resources:
  - federations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcs.crd.antrea.io
  resources:
  - federations/status
  verbs:
  - get
