# permissions for end users to view multiclustersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterset-viewer-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - multiclustersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - multiclustersets/status
  verbs:
  - get
