# permissions for end users to edit multiclustersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterset-editor-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - multiclustersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - multiclustersets/status
  verbs:
  - get
